server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

application:
  configurations:
    exchange: library_exchange
    saveBookKey: save_book_key
